### PR TITLE
Nested meta_queries to relate them via AND and inside via OR. Fixes #24

### LINKED ISSUE #24: Querying by multiple roles broken
As reported in the support forums: https://wordpress.org/support/topic/displaying-2-roles-doesnt-seem-to-work.

`[wp_team_list role="editor,contributor"]` currently also outputs admins etc. because of the `OR` in the meta query I guess.

Not sure when this actually happened, as I didn't really touch the user query stuff.

We can use `role__in` for 4.4+. For older versions, nested meta queries could work, e.g. `"visible" AND ( "role 1" OR "role 2")`

### PR DESCRIPTION
**Pull request by hubeRsen**
Should fix the issue, that all meta queries are related via OR, so capabilities and the hidden/visible flag will be recognized properly.

### CODE REVIEW

**Comment by swissspidy** [comment]
Does an issue exist for that bug? Haven't heard of that one :)

Unit tests? 😁 Maybe one day I guess...

**Comment by neverything** [comment]
There was an issue with this @swissspidy in the SBB Stories project apparently.

**Comment by hubeRsen** [comment]
Sure, issue #24

**Comment by hubeRsen** [comment]
Adjusted the plugin description according to #21

**Pull request merged**
